export const DOCUMENT_LIST_REQUEST = 'DOCUMENT_LIST_REQUEST';
export const DOCUMENT_LIST_SUCCESS = 'DOCUMENT_LIST_SUCCESS';
export const DOCUMENT_LIST_FAIL = 'DOCUMENT_LIST_FAIL';
export const DOCUMENT_LIST_RESET = 'DOCUMENT_LIST_RESET';

export const DOCUMENT_DELETE_REQUEST = 'DOCUMENT_DELETE_REQUEST';
export const DOCUMENT_DELETE_SUCCESS = 'DOCUMENT_DELETE_SUCCESS';
export const DOCUMENT_DELETE_FAIL = 'DOCUMENT_DELETE_FAIL';

export const DOCUMENT_DETAILS_REQUEST = 'DOCUMENT_DETAILS_REQUEST';
export const DOCUMENT_DETAILS_SUCCESS = 'DOCUMENT_DETAILS_SUCCESS';
export const DOCUMENT_DETAILS_FAIL = 'DOCUMENT_DETAILS_FAIL';
export const DOCUMENT_DETAILS_RESET = 'DOCUMENT_DETAILS_RESET';

export const DOCUMENT_EDITOR_ADD_REQUEST = 'DOCUMENT_EDITOR_ADD_REQUEST';
export const DOCUMENT_EDITOR_ADD_SUCCESS = 'DOCUMENT_EDITOR_ADD_SUCCESS';
export const DOCUMENT_EDITOR_ADD_FAIL = 'DOCUMENT_EDITOR_ADD_FAIL';
export const DOCUMENT_EDITOR_ADD_RESET = 'DOCUMENT_EDITOR_ADD_RESET';

export const DOCUMENT_EDITOR_REMOVE_REQUEST = 'DOCUMENT_EDITOR_REMOVE_REQUEST';
export const DOCUMENT_EDITOR_REMOVE_SUCCESS = 'DOCUMENT_EDITOR_REMOVE_SUCCESS';
export const DOCUMENT_EDITOR_REMOVE_FAIL = 'DOCUMENT_EDITOR_REMOVE_FAIL';
export const DOCUMENT_EDITOR_REMOVE_RESET = 'DOCUMENT_EDITOR_REMOVE_RESET';
